name: Publish Data Imports Project

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install sbt
        run: |
          echo "Installing sbt..."
          curl -L "https://github.com/sbt/sbt/releases/download/v1.9.5/sbt-1.9.5.tgz" | tar xz
          sudo mv sbt /usr/local/bin
          sudo ln -s /usr/local/bin/sbt/bin/sbt /usr/local/bin/sbt
          # Add sbt to the PATH to ensure it's accessible globally
          echo "PATH=\$PATH:/usr/local/bin/sbt/bin" >> $GITHUB_ENV
          
      - name: Cache SBT
        uses: coursier/cache-action@v6

      - name: Check sbt version
        run: sbt sbtVersion  # Verify sbt installation

      - name: Publish to GitHub Packages
        run: sbt clean compile publish
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
